// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE7ETcg53CtTPsLDK0MtycnU6zvwHOdfI',
    appId: '1:1045777718518:web:2a003cd0262d2d1a1760d7',
    messagingSenderId: '1045777718518',
    projectId: 'box-cricket-apphp2309',
    authDomain: 'box-cricket-apphp2309.firebaseapp.com',
    storageBucket: 'box-cricket-apphp2309.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5DgEYLFuThC8jJoUnwB2vHouBMvJ8V4',
    appId: '1:1045777718518:android:1e3d75d9caf7a8dc1760d7',
    messagingSenderId: '1045777718518',
    projectId: 'box-cricket-apphp2309',
    storageBucket: 'box-cricket-apphp2309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNO47v2K2QJzrDKp6zLqwjP6EG7YoALZQ',
    appId: '1:1045777718518:ios:6687b3c3d5a5b75c1760d7',
    messagingSenderId: '1045777718518',
    projectId: 'box-cricket-apphp2309',
    storageBucket: 'box-cricket-apphp2309.firebasestorage.app',
    iosBundleId: 'com.example.turfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNO47v2K2QJzrDKp6zLqwjP6EG7YoALZQ',
    appId: '1:1045777718518:ios:6687b3c3d5a5b75c1760d7',
    messagingSenderId: '1045777718518',
    projectId: 'box-cricket-apphp2309',
    storageBucket: 'box-cricket-apphp2309.firebasestorage.app',
    iosBundleId: 'com.example.turfApp',
  );
}
